# Generated by Django 4.2.23 on 2025-06-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0001_initial'),
        ('staff', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab.testrequest'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tests', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labtest'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.testcategory'),
        ),
    ]
