# Generated by Django 4.2.23 on 2025-06-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_CALL', 'On Call'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15)),
                ('last_maintenance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=10, unique=True)),
                ('pickup_location', models.TextField()),
                ('dispatch_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('distance_covered', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=10, unique=True)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('chief_complaint', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('SEVERE', 'Severe'), ('MODERATE', 'Moderate'), ('MILD', 'Mild')], max_length=20)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('TRIAGE', 'In Triage'), ('TREATMENT', 'Under Treatment'), ('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred'), ('DECEASED', 'Deceased')], default='REGISTERED', max_length=20)),
                ('vital_signs', models.TextField()),
                ('initial_diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('relationship', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_time', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.TextField()),
                ('medications', models.TextField()),
                ('notes', models.TextField()),
                ('emergency_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.emergencycase')),
            ],
        ),
    ]
