# Generated by Django 4.2.23 on 2025-06-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('staff', '0001_initial'),
        ('emergency', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencytreatment',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='emergencycase',
            name='assigned_bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.bed'),
        ),
        migrations.AddField(
            model_name='emergencycase',
            name='attending_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='emergencycase',
            name='emergency_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emergency.emergencycontact'),
        ),
        migrations.AddField(
            model_name='emergencycase',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='ambulancecall',
            name='ambulance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.ambulance'),
        ),
        migrations.AddField(
            model_name='ambulancecall',
            name='emergency_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.emergencycase'),
        ),
    ]
