# Generated by Django 4.2.23 on 2025-06-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('floors', models.PositiveIntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('MEDICAL', 'Medical Equipment'), ('LAB', 'Laboratory Equipment'), ('IT', 'IT Equipment'), ('FURNITURE', 'Furniture'), ('OTHER', 'Other')], max_length=20)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField()),
                ('last_maintenance', models.DateField()),
                ('next_maintenance', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.PositiveIntegerField()),
                ('ward_type', models.CharField(choices=[('GENERAL', 'General Ward'), ('PRIVATE', 'Private Room'), ('ICU', 'Intensive Care Unit'), ('CCU', 'Critical Care Unit'), ('EMERGENCY', 'Emergency Ward'), ('OT', 'Operation Theater')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.building')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('performed_by', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_maintenance', models.DateField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.ward'),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.ward')),
            ],
        ),
    ]
