# Generated by Django 4.2.23 on 2025-06-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
